baseURL = 'https://yanaezani.github.io/fleetros-user-docs/'
title = 'Fleetros Docs'

[module]
  [[module.imports]]
    path = "github.com/alex-shpak/hugo-book"

[params]
  BookTheme = 'auto'
  BookToC = true
  BookSection = 'docs'
  BookSearch = true
  BookBrand = 'FLEETROS'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
